### ISSUE TITLE
Name .md files with the title

### ISSUE THREAD

**Issue by asakura42** [crholm/mark#1]

**Comment by crholm** [comment]
Could you elaborate? 

Have been mening to get around to doing something to allow for easier selection of files. ie Including titles and tags

**Comment by asakura42** [comment]
I like the simplicity of your program, but `mark ls` has very uninformative output in my opinion. I propose to append title or first note's words to the filename. Like not `2022-09-12_20:16:41Z_Monday.md` but `New_Note_2022-09-12_20:16:41Z_Monday.md` or `these_are_first_five_words_2022-09-12_20:16:41Z_Monday.md`.

Also, for better choosing notes maybe use fzf library?

I can't do it myself because I don't know Golang.

**Comment by asakura42** [comment]
But maybe I don't understand the logic.

**Comment by crholm** [comment]
I see,  well the structure of naming is to keep the files chronologically ordered. The problem with `mark ls` is however obvious from the perspective you raise. Improving `mark ls` and having it nicely interact with `fzf` and/or `ripgrep` would be nice.  

(I primarily use it with tags instead of relying of file structure, eg. `:todo`.  then `mark page :todo` will yield what i'm looking for.)

i'll see if i can carve out some time this week to have a look at it.

**Comment by asakura42** [comment]
~~Also, @crholm I can't search by UTF-8 strings. How to fix it? For example~~

I'll better open other issue.

**Comment by crholm** [comment]
This is now addressed in
[a03cca2](https://github.com/crholm/mark/commit/a03cca268e0a56322229a23365f65d179f71bfbb)

While the basic structure file structure depends on the date, support surrounding titles and tags are now built out.

eg
```bash
mark ll   ## displays titles and tags along with file names
```

Accommodation for specific note selector / picker has been also made

eg.
```bash
export MARK_PICKER="fzf --preview \"mark cat {1}\""
mark edit
mark page --pick todo
```

or 

```bash
export MARK_PICKER="fzf"
export MARK_PICKER_MODE="grep"
mark edit
mark page --pick todo
```


which should cover the use case you were looking for?

edit:
```
 env GOPROXY=direct go install github.com/crholm/mark/cmd/mark@latest
```

**Comment by crholm** [comment]
closing this issue after fix
